/* Populated by react-webpack-redux:action */
export const ActionNames = {

  LOGIN:"LOGIN",
  LOGGING_IN:"LOGGING_IN",
  LOGIN_SUCCESS:"LOGIN_SUCCESS",
  LOGIN_FAILURE:"LOGIN_FAILURE",
  LOGOUT:"LOGOUT",

  CONTAINER_REFRESH:"CONTAINER_REFRESH",

  VIEW_FETCH:"VIEW_FETCH",
  VIEW_FETCHING:"VIEW_FETCHING",
  VIEW_FETCH_SUCCESS:"VIEW_FETCH_SUCCESS",
  VIEW_FETCH_FAILED:"VIEW_FETCH_FAILED",
  VIEW_ITEM_REMOVE:"VIEW_ITEM_REMOVE",

  ENTITY_GET:"ENTITY_GET",
  ENTITY_GETTING:"ENTITY_GETTING",
  ENTITY_GET_SUCCESS:"ENTITY_GET_SUCCESS",
  ENTITY_GET_FAILED:"ENTITY_GET_FAILED",

  ENTITY_SAVE:"ENTITY_SAVE",
  ENTITY_SAVING:"ENTITY_SAVING",
  ENTITY_SAVE_SUCCESS:"ENTITY_SAVE_SUCCESS",
  ENTITY_SAVE_FAILURE:"ENTITY_SAVE_FAILURE",

  ENTITY_PUT:"ENTITY_PUT",
  ENTITY_PUTTING:"ENTITY_PUTTING",
  ENTITY_PUT_SUCCESS:"ENTITY_UPDATE_SUCCESS",
  ENTITY_PUT_FAILURE:"ENTITY_PUT_FAILURE",


  ENTITY_UPDATE:"ENTITY_UPDATE",
  ENTITY_UPDATING:"ENTITY_UPDATING",
  ENTITY_UPDATE_SUCCESS:"ENTITY_UPDATE_SUCCESS",
  ENTITY_UPDATE_FAILURE:"ENTITY_UPDATE_FAILURE",


  PAGE_CHANGE: "@@reduxdirector/LOCATION_CHANGE",

  ENTITY_DELETE:"ENTITY_DELETE",
  ENTITY_DELETING:"ENTITY_DELETING",
  ENTITY_DELETE_SUCCESS:"ENTITY_DELETE_SUCCESS",
  ENTITY_DELETE_FAILURE:"ENTITY_DELETE_FAILURE"
}
