version: 0.0.1
description: Module provides designer dependencies
ui:
  js:
    buildDependencies: true
    externals:
      react: react
      react-dom: react-dom
    packages:
      babel-polyfill: "^6.26.0"
      redux: "^4.0.4"
      react-redux: "^7.1.1"
      redux-form: "^8.2.6"
      axios: "^0.19.0"
      md5: "^2.2.1"
      sanitize-html: "^1.20.1"
      director: "^1.2.8"
      redux-director: "^0.2.9"
      redux-saga: "^1.1.1"
      core-js: "^3.2.1"
      prop-types: "^15.7.0"
