version: 0.0.1
dependencies:
  reactwebcommon: ">=0.0.1"
  uicommon: ">=0.0.1"
  authui: ">=0.0.1"
description: Module provides laatoo forms for applications
ui:
  externals:
    babel-runtime: babel-runtime
    babel-polyfill: babel-polyfill
    redux-form: redux-form
    react: react
    react-redux: react-redux
    react-dom: react-dom
    authui: authui
    redux-saga: redux-saga
    reactwebcommon: reactwebcommon
    uicommon: uicommon
  packages:
    react: "^16.1.0"
    redux-form: "^7.1.1"
    redux-saga: "^0.16.0"
