version: 0.0.1
dependencies:
  reactwebcommon: ">=0.0.1"
  authui: ">=0.0.1"
description: Module provides laatoo forms for applications
ui:
  skipUIModules: true
  externals:
    babel-runtime: babel-runtime
    babel-polyfill: babel-polyfill
    redux-form: redux-form
    react: react
    react-redux: react-redux
    react-dom: react-dom
    authui: authui
    reactwebcommon: reactwebcommon
  packages:
    react: "^15.6.1"
    redux-form: "^7.1.1"
