version: "0.0.1"
dependencies:
description: "Module provides ui base components. "
objects:
ui:
  js:
    skipUIModules: true
    packages:
      axios: "^0.19.0"
      core-js: "^2.5.7"
    externals:
      axios: axios
      react: react
      core-js: core-js
