version: 0.0.1
dependencies:
  uicommon: ">=0.0.1"
  reactwebcommon: ">=0.0.1"
description: Module provides material ui kit for laatoo applications
objects: {}
ui:
  js:    
    externals:
      redux-form: redux-form
      react: react
      reactwebcommon: reactwebcommon
      react-redux: react-redux
      react-dom: react-dom
      uicommon: uicommon
      prop-types: prop-types
    packages:
      react: "^16.8.0"
      react-dom: "^16.8.0"
      react-redux: "^7.1.0"
      "@material-ui/core": "3.9.0"
      redux-form: "^8.2.6"
      react-tap-event-plugin: "*"
      prop-types: "^15.7.0"
