version: 0.0.1
dependencies:
  uicommon: ">=0.0.1"
  reactwebcommon: ">=0.0.1"
description: Module provides material ui kit for laatoo applications
objects: {}
ui:
  js:    
    overwriteJSMods: true
    externals:
      react: react
      reactwebcommon: reactwebcommon
      redux: redux
      react-redux: react-redux
      react-dom: react-dom
      uicommon: uicommon
      prop-types: prop-types
    packages:
      react: "^16.8.0"
      react-dom: "^16.8.0"
      redux: "^4.0.4"
      hoist-non-react-statics: "^3.3.0"
      react-redux: "^7.1.0"
      "@material-ui/core": "^4.4.0"
      "@material-ui/styles": "^4.4.0"
      "jss": "^10.0.0"
      react-tap-event-plugin: "*"
      prop-types: "^15.7.0"
