version: 0.0.1
dependencies:
  reactwebcommon: ">=0.0.1"
  uicommon: ">=0.0.1"
  reactpages: ">=0.0.1"
  modulesbase: ">=0.0.1"
  modulesrepository: ">=0.0.1"
  laatoositeui: ">=0.0.1"
description: Module provides module designer entities ui 
modules:
  moduledesignentities:
    module: entity
    settings:
      object: ModuleDesignEntities
      parent: root
      instance: ModuleDesignEntities
      dataservicefactory: mongodatabase
      create_dataadapterfactory: true
      create_dataservice: true
      create_updateservice: true
      create_objectchannel: true
      create_getservice: true
      update_form: true
  entity:
    module: entity
    settings:
      object: EntityDesign
      parent: root
      instance: EntityDesign
      skipData: true
      list_view: true
      new_form: true
      new_form_page: true      
  field:
    module: entity
    settings:
      object: FieldDesign
      parent: root
      instance: FieldDesign
      skipData: true
      list_view: true
      new_form: true
      new_form_page: true      
  widget:
    module: entity
    settings:
      object: FieldWidgetDesign
      parent: root
      instance: FieldWidgetDesign
      skipData: true
      list_view: true
      new_form: true
      new_form_page: true      
ui:
  js:
    externals:
      react: react
      uicommon: uicommon
      reactpages: reactpages
      reactwebcommon: reactwebcommon
    packages:
      react: "^16.3.0"
