version: 0.0.1
dependencies:
  uicommon: ">=0.0.1"
  reactwebcommon: ">=0.0.1"
description: This module provides authentication ui components
ui:
  skipUIModules: true
  packages:
    axios: "^0.16.2"
    babel-polyfill: "^6.26.0"
    babel-runtime: "^6.26.0"
    prop-types: "^15.6.0"
    md5: "^2.2.1"
    react-redux: "^5.0.6"
    redux: "^3.7.2"
    redux-saga: "^0.16.0"
  externals:
    axios: axios
    babel-polyfill: babel-polyfill
    babel-runtime: babel-runtime
    prop-types: prop-types
    react: react
    uicommon: uicommon
    md5: md5
    react-redux: react-redux
    redux: redux
    redux-saga: redux-saga
    reactwebcommon: reactwebcommon
