version: 0.0.1
dependencies:
  uicommon: ">=0.0.1"
description: 'Module provides web common components. '
ui:
  js:
    skipUIModules: true
    externals:
      react: react
      sanitize-html: sanitize-html
      uicommon: uicommon
      redux: redux
      react-redux: react-redux
      core-js: core-js
    packages:
      react: "^16.1.0"
      sanitize-html: "^1.14.1"
      redux: "^3.7.2"
      react-redux: "^5.0.6"
      core-js: "^2.5.7"
