FROM golang:latest

RUN groupadd -r laatoo -g 1000

RUN useradd -u 1000 -ms /bin/bash -g laatoo -G sudo -p laatoo laatoo

RUN mkdir -p /laatoo

ENV LAATOO_SDK=/laatoo/sdk

RUN mkdir -p $LAATOO_SDK

ENV LAATOO_RUST_CLIENT_SDK=$LAATOO_SDK/client/rust

RUN chown -R laatoo.root /laatoo

WORKDIR /go

ENTRYPOINT /bin/bash
