FROM laatoobase:latest

RUN mkdir -p /go/src/laatoo

COPY sdk /go/src/laatoo/sdk

RUN mkdir -p /plugin/src

RUN mkdir -p /plugin/dist

COPY plugincompiler.sh /compile.sh

VOLUME /plugin

ENV GOPATH=$GOPATH:/plugin

ENV name=plugin

ENV package=.

WORKDIR /plugin/src

ENTRYPOINT /compile.sh /plugin/bin/$name.so $package
