FROM laatoomodulebuilder:latest
#FROM gcr.io/distroless/base:latest

COPY list /

VOLUME /laatoobin

COPY cpplibs/* /usr/lib/

COPY cpplibs.conf /etc/ld.so.conf.d/

COPY dist/config /config

ENV LAATOO_CONFIGDIR /config

WORKDIR /laatoobin

ENTRYPOINT ["/laatoobin/laatoo"]
