version: 0.0.1
description: 'Module provides sign up support for laatoo. Registration with and without workflow support is supported'
objects:
  REGISTRATION:
    type: service
    description: This service allows registration of users in the database.
    request:
      type: stringmap
    configurations:
      user_data_svc:
        type: string
        required: true
        description: User data service for registration service
      def_role:
        type: string
        required: true
        description: Default role to be assigned to a new user
      emailverification:
        type: bool
        description: Verify email
        variable: VerifyEmail
      emailqueue:
        type: string
        description: Queue to use for sending emails incase a workflow is not configured
        variable: Queue
      emailworkflowsupport:
        type: bool
        description: Verify email using workflow
        variable: VerifyWithWorkflow
      emailverificationworkflow:
        type: string
        description: Verify email using provided workflow
        variable: WorkflowName
      workflowinitiator:
        type: string
        description: Verify email using provided workflow
        inject: WorkflowInitiator
  SignupEmailTask:
    type: service
    description: Task processor for signup email tasks.
    configurations:
      SiteName: 
        type: string
        description: Site name to use in email body
        variable: SiteName
        required: true
      SiteLink: 
        type: string
        description: Link to use for verifying email
        required: true
        variable: SiteLink
      MailBody: 
        type: string
        description: Mail body to use for emails
        required: true
        variable: MailBody
      Key: 
        type: string
        required: true
        description: Key to use for signing token
        variable: Key
    request:
      params:
        Task:
          type: bytes
          description: Bytes containing string map for signup task
  VerifyEmailService:
    type: service
    description: Service providing verification of email tokens.
    configurations:
      Key: 
        type: string
        required: true
        description: Key to use for signing token
        variable: Key
      emailworkflowsupport:
        type: bool
        description: Verify email using workflow
        variable: VerifyWithWorkflow
    request:
      params:
        token: 
          type: string
          description: Token for verifying email
params:
  sitename: 
    type: string
    description: Site name to use in email body
  sitelink: 
    type: string
    description: Link for the main site
  mailbody: 
    type: string
    description: Mail body to use for emails
  key: 
    type: string
    description: Key to use for signing token
  emailverification:
    type: bool
    description: Workflow support for registration process
  emailqueueconsumer:
    type: string
    description: Email queue consumer service. Not required unless override the system default queue consumer
  emailqueuepublisher:
    type: string
    description: Email queue consumer service. Not required unless override the system default queue publisher
  emailworkflowsupport:
    type: string
    description: Use workflow for email verification
  workflowinitiator:
    type: string
    description: Workflow initiator service to use for starting workflow if workflow support for email verification is required
  emailverificationworkflow:
    type: string
    description: Workflow to be used for email verification
