version: 0.0.1
description: 'Module provides sign up support for laatoo. Registration with and without workflow support is supported'
objects:
  REGISTRATION:
    type: service
    description: This service allows registration of users in the database.
    request:
      type: stringmap
    configurations:
      user_data_svc:
        type: string
        required: true
        description: User data service for registration service
      def_role:
        type: string
        required: true
        description: Default role to be assigned to a new user
      emailverification:
        type: bool
        description: Verify email
        variable: VerifyEmail
      SiteName: 
        type: string
        description: Site name to use in email body
        variable: SiteName
        required: true
      SiteLink: 
        type: string
        description: Link to use for verifying email
        required: true
        variable: SiteLink
      MailBody: 
        type: string
        description: Mail body to use for emails
        required: true
        variable: MailBody
      Key: 
        type: string
        required: true
        description: Key to use for signing token
  VerifyEmailService:
    type: service
    description: Task processor for signup email tasks.
    configurations:
      Key: 
        type: string
        required: true
        description: Key to use for signing token
    request:
      params:
        token: 
          type: string
          description: Token for verifying email
params:
  sitename: 
    type: string
    description: Site name to use in email body
  sitelink: 
    type: string
    description: Link for the main site
  mailbody: 
    type: string
    description: Mail body to use for emails
  key: 
    type: string
    description: Key to use for signing token
  emailverification:
    type: bool
    description: Workflow support for registration process
