#skip: {{if exists "signup_support"}} {{var "signup_support" | not}} {{else}} true {{end}}
parent: root
service: signup.register
method: POST
path: "/register"
skipauth: true
bodyparamname: credentials
