users:
  method: POST
  url: "/user/view"
applicationsview:
  method: POST
  url: "/application/view"
modulesrepoview:
  method: POST
  url: "/moduledefinition/view"
applicationresolver:
  method: POST
  url: "/resolve/application"
environmentresolver:
  method: POST
  url: "/resolve/environment"
serverresolver:
  method: POST
  url: "/resolve/server"
