users:
  method: POST
  url: "/user/view"
solution.applications:
  method: POST
  url: "/application/view"
solution.environments:
  method: POST
  url: "/environment/view"
solution.servers:
  method: POST
  url: "/server/view"
applicationresolver:
  method: POST
  url: "/resolve/application"
environmentresolver:
  method: POST
  url: "/resolve/environment"
serverresolver:
  method: POST
  url: "/resolve/server"
modulesrepoview:
  method: POST
  url: "/moduledefinition/view"
entitlementmodule:
    method: POST
    url: "/entitlement/view"
    responseField: Module
