version: 0.0.1
dependencies:
  reactwebcommon: ">=0.0.1"
  entity: ">=0.0.1"
  uicommon: ">=0.0.1"
  reactpages: ">=0.0.1"
  itemdetailview: ">=0.0.1"
description: Module provides repository
objects: {}
modules:
  moduledefinition:
    module: entity
    settings:
      object: ModuleDefinition
      parent: root
      instance: ModuleDefinition
      dataservicefactory: mongodatabase
ui:
  skipUIModules: true
  externals:
    react: react
    reactwebcommon: reactwebcommon
    itemdetailview: itemdetailview
    uicommon: uicommon
    reactpages: reactpages
  packages:
    react: "^16.3.0"
