version: 0.0.1
dependencies:
  reactwebcommon: ">=0.0.1"
  reactpages: ">=0.0.1"
  entity: ">=0.0.1"
  uicommon: ">=0.0.1"
  itemdetailview: ">=0.0.1"
description: Module provides repository
objects: 
  repositoryimport:
    type: service
    description: Module import service. Uploaded files are passed to this service
    request:
      params:        
        Data:
          type: stringsmap
  configformsbuilder:
    type: service
    description: Creates UI configuration forms for modules. UI plugin
  entitlementcreator:
    type: service
    description: Entitlement service that creates entitlements after a module has been uploaded
    request:
      params:        
        Data:
          type: stringsmap
        solutionId:
          type: string
        moduleId:
          type: string
  repositoryupdate:
    type: service
    description: Module update service. Updates files from file name passed to this service
    request:
      params:        
        module:
          type: string
modules:
  moduledefinition:
    module: entity
    settings:
      object: ModuleDefinition
      parent: root
      instance: ModuleDefinition
      dataservicefactory: mongodatabase
  entitlements:
    module: entity
    settings:
      object: Entitlement
      parent: root
      instance: Entitlement
      dataservicefactory: mongodatabase
      embedded_doc_search: true
      list_view_args: 
        Solution: 
          Id: {{jsreplace "Application.Route.Params.solutionId"}}
      form_new_args:
        Solution: 
          Id: {{jsreplace "Application.Route.Params.solutionId"}}
          Type: Solution
ui:
  js:
    externals:
      react: react
      reactwebcommon: reactwebcommon
      itemdetailview: itemdetailview
      uicommon: uicommon
      reactpages: reactpages
      core-js: core-js
    packages:
      react: "^16.3.0"
      core-js: "^2.5.7"
