name: uiapp.files{{var "application" "."}}
servicemethod: named_files_service
files:
  modules.js:
    cache: {{var "cachefiles"}}
    path: /scripts/modules{{var "application" "."}}.js
  components.conf.js:
    cache: {{var "cachefiles"}}
    path: /scripts/components{{var "application" "."}}.conf.js
  boot.js:
    cache: {{var "cachefiles"}}
    path: /scripts/boot{{var "application" "."}}.js
  app.css:
    cache: {{var "cachefiles"}}
    path: /css/app{{var "application" "."}}.css
  wasm.json:
    cache: {{var "cachefiles"}}
    path: /wasm/wasm{{var "application" "."}}.json
  vendor.js:
    cache: {{var "cachefiles"}}
    path:  /scripts/vendor{{var "application" "."}}.js
storage: uiapp.filesstorage{{var "application" "."}}
