name: uiapp.files{{var "application" "."}}
servicemethod: named_files_service
files:
  app.js:
    cache: {{var "cachefiles"}}
    path: /scripts/app{{var "application" "."}}.js
  services.conf.js:
    cache: {{var "cachefiles"}}
    path: /scripts/services{{var "application" "."}}.conf.js
  app.css:
    cache: {{var "cachefiles"}}
    path: /css/app{{var "application" "."}}.css
  wasm.json:
    cache: {{var "cachefiles"}}
    path: /wasm/wasm{{var "application" "."}}.json
  vendor.js:
    cache: {{var "cachefiles"}}
    path:  /scripts/vendor{{var "application" "."}}.js
storage: uiapp.filesstorage{{var "application" "."}}
