name: uiapp.files{{var "application" "."}}
servicemethod: named_files_service
files:
  app.js:
    cache: 'false'
    path: /scripts/app{{var "application" "."}}.js
  services.conf.js:
    cache: 'true'
    path: /scripts/services{{var "application" "."}}.conf.js
  app.css:
    cache: 'true'
    path: /css/app{{var "application" "."}}.css
  vendor.js:
    cache: 'true'
    path:  /scripts/vendor{{var "application" "."}}.js
storage: uiapp.filesstorage{{var "application" "."}}
