name: uiapp{{var "application" "."}}
servicemethod: ui
ModuleManagerPlugin: true
mergeduifile:  app{{var "application" "."}}.js
mergedcssfile: app{{var "application" "."}}.css
mergedwasm: wasm{{var "application" "."}}.json
mergeduidescriptor: services{{var "application" "."}}.conf.js
mergedvendorfile: vendor{{var "application" "."}}.js
properties_ext: {{var "application" "."}}.json
application: {{var "application"}}
hotmodules: {{var "hotmodules"}}
