version: 0.0.1
description: This module provides access to vault secrets service
objects:
  vaultsecrets.VaultSecretsSvc:
    type: service
    description: Vaults secret store service
    configurations:
      host:
        description: Host to connect
        type: string
        required: true
      path:
        description: Path to prepend to secrets
        type: string
        required: true
params:
  host: 
    type: string
    description: Host to connect
  path:
    description: Path to prepend to secrets
    type: string
    required: true
