[package]
name = "websocket"
version = "0.1.0"
authors = ["Mandeep Singh Brar <mandeep@virsainfomedia.com>"]

[profile.release]
debug = false
lto = true

[dependencies]
wasm-bindgen = "^0.2.25"
laatoocore = { path = "/go/src/laatoo/sdk/client/rust/laatoocore" }



[lib]
crate-type = ["cdylib"]
