/* Populated by react-webpack-redux:action */
export const ActionNames = {

  CONTAINER_REFRESH:"CONTAINER_REFRESH",

  VIEW_FETCH:"VIEW_FETCH",
  VIEW_FETCHING:"VIEW_FETCHING",
  VIEW_FETCH_SUCCESS:"VIEW_FETCH_SUCCESS",
  VIEW_FETCH_FAILED:"VIEW_FETCH_FAILED",
  VIEW_ITEM_REMOVE:"VIEW_ITEM_REMOVE",
  VIEW_ITEM_RELOAD: "VIEW_ITEM_RELOAD",

  GROUP_LOAD:"GROUP_LOAD",
}
