/* Populated by react-webpack-redux:action */
export const ActionNames = {

  CONTAINER_REFRESH:"CONTAINER_REFRESH",

  VIEW_FETCH:"VIEW_FETCH",
  VIEW_FETCHING:"VIEW_FETCHING",
  VIEW_FETCH_SUCCESS:"VIEW_FETCH_SUCCESS",
  VIEW_FETCH_FAILED:"VIEW_FETCH_FAILED",
  VIEW_ITEM_REMOVE:"VIEW_ITEM_REMOVE",
  VIEW_ITEM_RELOAD: "VIEW_ITEM_RELOAD",

  ENTITY_VIEW_FETCH:"ENTITY_VIEW_FETCH",
  ENTITY_VIEW_FETCHING:"ENTITY_VIEW_FETCHING",
  ENTITY_VIEW_FETCH_SUCCESS:"ENTITY_VIEW_FETCH_SUCCESS",
  ENTITY_VIEW_FETCH_FAILED:"ENTITY_VIEW_FETCH_FAILED",

  PAGE_CHANGE: "@@reduxdirector/LOCATION_CHANGE",

  GROUP_LOAD:"GROUP_LOAD",
}
