loginForm:
  loginBtnText: Login
  google: Google
  separator: Or
  formtext: 'Please Log In with '
  userlabel: Username or email
  userplaceholder: Email
  passwordlabel: Password
  passwordplaceholder: Password
signupForm:
  signupBtnText: Register
  formtext: 'Sign up'
  userlabel: Email
  userplaceholder: Email
  passwordlabel: Password
  passwordplaceholder: Password
  confirmpasswordlabel: Confirm Password
  confirmpasswordplaceholder: Confirm Password
errors:
  passwordmismatch: Passwords do not match