version: 0.0.1
description: 'Module provides static file services. '
objects:
  staticfileserver.StaticFiles:
    type: service
    description: This service serves static files from a storage component
    configurations:
      storage:
        description: Storage service from which files are to be served
        type: string
        required: true
      bucket:
        description: Bucket in storage service from where files are to be served
        type: string
      operation:
        description: Operation to perform on a file
        type: string
      transformedstorage:
        description: Storage to be used for keeping transformed files
        type: string
      default:
        description: File to be used in case a file is not avilable
        type: string
      width:
        description: Width of a transformed image file
        type: string
      height:
        description: Height of a transformed image file
        type: string
    request:
      params:
        file:
          description: File to be served by this service
          type: string
          required: true
  staticfileserver.NamedFileService:
    type: service
    description: This service serves named files from a storage component. Only disk
      files are supported
    configurations:
      storage:
        description: Storage service from which files are to be served
        type: string
        required: true
      files:
        description: File and path mapping
        type: config
        required: true
    request:
      params:
        file:
          description: File to be served by this service
          type: string
          required: true
  staticfileserver.TemplateFileService:
    type: service
    description: This service converts files with name.tpl extension to name files
      by applying golang text template package. Method var is provided to access variables
      in context
    configurations:
      templatefilesdirectory:
        description: Directory containing template files. defaults to files folder
          of module
        type: string
      processedfilesdirectory:
        description: Directory containing processed files. defaults to templates directory
        type: string
      templatesmap:
        description: Map of output file names to template file name
        type: config
  staticfileserver.BundledFileService:
    type: service
    description: This service serves named files from a storage component. Only disk
      files are supported
    configurations:
      storage:
        description: Storage service from which files are to be served
        type: string
        required: true
      bundles:
        description: File and path mapping
        type: config
        required: true
    request:
      params:
        bundle:
          description: Bundle to be served by this service
          type: string
          required: true
