version: 0.0.1
dependencies:
  entity: ">=0.0.1"
description: Module provides environment entity
modules:
  default:
    module: entity
    settings:
      object: Environment
      parent: root
      instance: Environment
      dataservicefactory: mongodatabase
ui:
  skipUIModules: true
