version: 0.0.1
description: 'Module provides database login and registration services. '
objects:
  dblogin.LoginService:
    type: service
    description: This service allows logins for users in the database.
    request:
      type: string
    configurations:
      user_data_svc:
        type: string
        required: true
        description: User data service for login service
  dblogin.LogoutService:
    type: service
    description: This service allows logouts for users in the database.
