version: 0.0.1
dependencies:
  uicommon: ">=0.0.1"
  reactpages: ">=0.0.1"
description: Module provides base for react based applications of laatoo.
ui:
  js:
    externals:
      react: react
      react-redux: react-redux
      reactpages: reactpages
      uicommon: uicommon
      redux: redux
      redux-saga: redux-saga
      prop-types: prop-types
      core-js: core-js
    packages:
      react: "^16.8.0"
      react-redux: "^7.0.0"
      redux: "^4.0.4"
      redux-saga: "^1.1.1"
      prop-types: "^15.6.0"
      core-js: "^2.5.7"
params:
  uikit: 
    type: string
    description: Uikit to be used by laatoo react application
  theme: 
    type: string
    description: Theme to be used by laatoo react application
  router: 
    type: string
    description: Router to be used by laatoo react application
  uiapplication: 
    type: string
    description: Ui application for which application is being started
