version: 0.0.1
description: This module provides redis pub sub implementation. A service 'laatoo.redispubsub'
  is created by default that connects to localhost:6379 and databse 0
objects:
  redispubsub.RedisPubSubService:
    type: service
    description: This service provides component for redis pubsub implementation
    configurations:
      redispubsubserver:
        description: Address of redis server
        type: string
        default: ":6379"
      redispubsubdb:
        description: Redis db to be used for pubsub
        type: string
        default: ":0"
      encoding:
        description: Encoding to be used while working with redis
        type: string
        default: binary
params:
  redispubsubserver: 
    description: Address of redis server
    type: string
  redispubsubdb: 
    description: Redis db to be used for pubsub
    type: string
