version: 0.0.1
description: 'Module provides sql connection services. Component Service created from
  this factory must be provided ''object'' specifying the object to manage. Optional
  environment variables for service include ''collection'', ''auditable'', ''cacheable'',
  ''presave'', ''postupdate'', ''postload'', ''auditable''. Factory ''sqldatabase''
  is created by default using environment variables ''sqlconnectionstring'' '
objects:
  sql_services:
    type: factory
    description: SQL Database connection services
    configurations:
      sqlconnectionstring:
        description: Connection string for sql database
        type: string
        required: true
      sqlvendor:
        description: Database vendor used. Vendors specified by gorm are supported
        type: string
        required: true
