version: 0.0.1
dependencies:
  user: ">=0.0.1"
  role: ">=0.0.1"
  dataadapter: ">=0.0.1"
  dblogin: ">=0.0.1"
description: This module provides local database authentication system. Two services
  'login.local' and 'register' are provided along with http channels '/login' and
  '/register'
modules:
  roles:
    module: dataadapter
    settings:
      object: Role
      dataservicefactory: {{var "dataservicefactory"}}
  users:
    module: dataadapter
    settings:
      object: {{var "userobject"}}
      dataservicefactory: {{var "dataservicefactory"}}
params:
  userobject: 
    type: string
    description: User object to be used for local authentication
  dataservicefactory: 
    type: string
    description: Data service factory to be used for auth purposes
  defaultrole: 
    type: string
    description: Default role for the registered user
