version: 0.0.1
dependencies:
  reactwebcommon: ">=0.0.1"
  authui: ">=0.0.1"
  reactpages: ">=0.0.1"
description: Module provides laatoosite theme for laatoo applications
objects: {}
ui:
  js:
    externals:
      babel-runtime: babel-runtime
      babel-polyfill: babel-polyfill
      react: react
      react-redux: react-redux
      react-dom: react-dom
      authui: authui
      reactwebcommon: reactwebcommon
      reactpages: reactpages
      prop-types: prop-types
      core-js: core-js
    packages:
      react: "^16.1.0"
      react-dom: "^16.1.0"
      react-redux: "^5.0.6"
      core-js: "^2.5.7"
  settings:
    headerimage: Image used for header
    headertitle: Title used in header
    headerclass: Style to be used in header
    vertical: Vertical/Horizontal menus
params:
  authenticate:
    type: bool
    description: If authentication is required for this template
  vertical:
    type: bool
    description: Menu orientation
