version: 0.0.1
dependencies:
  reactwebcommon: ">=0.0.1"
  uicommon: ">=0.0.1"
description: Module provides file upload ui component
ui:
  js:
    externals:
      babel-runtime: babel-runtime
      reactwebcommon: reactwebcommon
      uicommon: uicommon
      babel-polyfill: babel-polyfill
      redux-form: redux-form
      react: react
      react-redux: react-redux
      react-dom: react-dom
      redux-saga: redux-saga
      prop-types: prop-types
      core-js: core-js
    packages:
      react: "^16.3.0"
      redux-form: "^7.1.1"
      redux-saga: "^0.16.0"
      react-dropzone: "^4.0.1"
      prop-types: "^15.6.0"
      core-js: "^2.5.7"
