version: 0.0.1
description: 'Module provides data store processing services for data pipeline'
dependencies: 
  datapipeline: 0.0.1
objects:
  datastoreprocessor.DataExporter:
    type: service
    description:  Data Importer service for use in data pipeleine. Save is done for all objects
    configurations:
      exportdataservice:
        type: string
        description: Data service to which list of objects is to be saved
        required: true
  datastoreprocessor.DataImporter:
    type: service
    description: Data Importer service for use in data pipeleine. GetList is done to get a list of all objects
    configurations:
      importdataservice:
        type: string
        description: Data service from which a list of objects has to be fetched
        required: true
