version: 0.0.1
description: 'Module provides email communication service'
objects:
  email.EmailService:
    type: service
    component: true
    description: Email service
    configurations:
      mailserver:
        description: mail server to use for sending emails
        type: string
        required: true
      mailport:
        description: mail port to use for sending emails. Colon to be included by user
        type: string
        variable: MailPort
      mailsender:
        description: email to use for sending emails
        type: string
        required: true
      mailpass:
        description: password to use for sending emails
        type: string
      queuetasks:
        description: send communication directly or queue them if received through communicator interface
        type: bool
        default: false
      emailqueue:
        description: queue to use for sending emails if queueing of tasks is to be done
        type: string
params:
  mailserver:
    description: mail server to use for sending emails
    type: string
  mailport:
    description: mail port to use for sending emails. Colon to be included by user
    type: string
  mailsender:
    description: email to use for sending emails
    type: string
  mailpass:
    description: password to use for sending emails
    type: string
  queuetasks:
    description: send communication directly or queue them if received through communicator interface
    type: bool
    default: false
  emailqueue:
    description: queue to use for sending emails if queueing of tasks is to be done
    type: string
