export default {
  DISPLAY_ERROR: "DISPLAY_ERROR",
  SHOW_MESSAGE: "SHOW_MESSAGE",
  SHOW_INTERACTION_COMP: "SHOW_INTERACTION_COMP",
  CLOSE_INTERACTION_COMP: "CLOSE_INTERACTION_COMP",
  LOGOUT:"LOGOUT"
}
