export default {
  DISPLAY_ERROR: "DISPLAY_ERROR",
  SHOW_MESSAGE: "SHOW_MESSAGE",
  SHOW_INTERACTION_COMP: "SHOW_INTERACTION_COMP",
  CLOSE_INTERACTION_COMP: "CLOSE_INTERACTION_COMP",
  LAATOO_ACTION: "LAATOO_ACTION",
  LOGOUT:"LOGOUT",
  PAGE_CHANGE: "@@reduxdirector/LOCATION_CHANGE"
}
