version: 0.0.1
description: Module provides pages laatoo applications
ui:
  skipUIModules: true
  externals:
    babel-runtime: babel-runtime
    babel-polyfill: babel-polyfill
    react: react
    react-redux: react-redux
    redux: redux
  packages:
    react: "^15.6.0"
    react-redux: "^5.0.6"
    redux: "^3.7.2"
