version: 0.0.1
dependencies:
  reactwebcommon: ">=0.0.1"
description: Module provides pages laatoo applications
ui:
  skipUIModules: true
  externals:
    babel-runtime: babel-runtime
    babel-polyfill: babel-polyfill
    react: react
    react-redux: react-redux
    redux: redux
    reactwebcommon: reactwebcommon
  packages:
    react: "^16.1.0"
    react-redux: "^5.0.6"
    redux: "^3.7.2"
