version: 0.0.1
description: 'Module provides error processing services for data pipeline'
dependencies: 
  datapipeline: 0.0.1
objects:
  memoryerrorprocessor:
    type: service
    description: Stores all errors in memory
