parent: root
service: login.local
method: POST
path: "/login"
skipauth: true
bodyparamname: credentials
responsehandler:
  name: {{if is "setcookies"}} CookiesResponseHandler {{else}} DefaultResponseHandler{{end}}