version: 0.0.1
dependencies:
  reactwebcommon: ">=0.0.1"
  uicommon: ">=0.0.1"
  authui: ">=0.0.1"
  reactpages: ">=0.0.1"
description: Module provides laatoo forms for applications
ui:
  js:
    externals:
      redux-form: redux-form
      react: react
      react-redux: react-redux
      react-dom: react-dom
      authui: authui
      redux-saga: redux-saga
      reactwebcommon: reactwebcommon
      reactpages: reactpages
      uicommon: uicommon
      prop-types: prop-types
      core-js: core-js
    packages:
      react: "^16.8.0"
      redux-form: "^8.2.1"
      redux-saga: "^1.1.0"
      prop-types: "^15.7.0"
      core-js: "^3.2.1"
