version: 0.0.1
description: 'Module provides email communication service'
objects:
  cadence_worker:
    type: service
    description: Worker for cadence workflow software
    configurations:
      Host:
        description: Host where cadence is running
        type: string
        required: true
        variable: Host
      Domain:
        description: Cadence domain
        type: string
        required: true
        variable: Domain
      TaskLists:
        description: Tasklists for which workers are to be created
        type: stringarray
        required: true
        variable: TaskLists
      ClientName:
        description: Client name
        type: string
        required: true
        variable: ClientName
      CadenceService:
        description: Cadence service
        type: string
        required: true
        variable: CadenceService
  cadence_simpleworkflow:
    type: service
    description: Simple sequential workflow for cadence
    configurations:
      taskListName:
        description: Tasklist name
        type: string
        variable: TaskListName
      workflowname:
        description: Workflow name
        type: string
        required: true
        variable: WorkflowName
      workflow:
        description: Array of tasks in the sequential workflow
        type: stringarray
        required: true
        variable: Tasks
  cadence_dslworkflow:
    type: service
    description: DSL workflow for cadence. Refer cadence samples. Support parallelization
    configurations:
      taskListName:
        description: Tasklist name
        type: string
        variable: TaskListName
      workflowname:
        description: Workflow name
        type: string
        required: true
        variable: WorkflowName
      workflow:
        description: Task structure for workflow
        type: config
        required: true
  cadence_workflowinitiator:
    type: service
    description: Service to initiate workflows
    configurations:
      Host:
        description: Host where cadence is running
        type: string
        required: true
        variable: Host
      Domain:
        description: Cadence domain
        type: string
        required: true
        variable: Domain
      ClientName:
        description: Client name
        type: string
        required: true
        variable: ClientName
      CadenceService:
        description: Cadence service
        type: string
        required: true
        variable: CadenceService
params:
  workflowdomain: 
    type: string
    description: Domain to use for workflow support
  workflowhost: 
    type: string
    description: Host for workflow
  workflowtasklists: 
    type: stringarray
    description: Tasklists for workers need to be started
  workflowclient:
    type: string
    description: Client name to be used for workers
  workflowservicename:
    type: string
    description: Name of workflow service
  workerservicename:
    type: string
    description: Name of worker service

#create domain on cadence using this command docker run --network=host --rm ubercadence/cli:master --do laatoo.defaultdomain domain register -rd 1
#docker run --network=host --rm ubercadence/cli:master --domain laatoo.defaultdomain domain describe

