version: 0.0.1
description: 'Module provides email communication service'
objects:
  cadence_worker:
    type: service
    description: Worker for cadence workflow software
    configurations:
      Host:
        description: Host where cadence is running
        type: string
        required: true
      Domain:
        description: Cadence domain
        type: string
        required: true
      TaskListName:
        description: Tasklist processed by worker
        type: string
        required: true
      ClientName:
        description: Client name
        type: string
        required: true
      CadenceService:
        description: Cadence service
        type: string
        required: true
  cadence_simpleworkflow:
    type: service
    description: Simple sequential workflow for cadence
    configurations:
      TaskListName:
        description: Tasklist name
        type: string
        required: true
        variable: TaskListName
      WorkflowName:
        description: Workflow name
        type: string
        required: true
        variable: WorkflowName
      Tasks:
        description: Array of tasks in the sequential workflow
        type: stringarray
        required: true
        variable: Tasks
  cadence_dslworkflow:
    type: service
    description: DSL workflow for cadence. Refer cadence samples. Support parallelization
    configurations:
      TaskListName:
        description: Tasklist name
        type: string
        required: true
        variable: TaskListName
      WorkflowName:
        description: Workflow name
        type: string
        required: true
        variable: WorkflowName
      Workflow:
        description: Task structure for workflow
        type: config
        required: true
  cadence_workflowinitiator:
    type: service
    description: Service to initiate workflows
    configurations:
      Host:
        description: Host where cadence is running
        type: string
        required: true
      Domain:
        description: Cadence domain
        type: string
        required: true
      ClientName:
        description: Client name
        type: string
        required: true
      CadenceService:
        description: Cadence service
        type: string
        required: true
      TaskListName:
        description: Tasklist name
        type: string
        required: true
      WorkflowDefinition:
        description: Workflow Definition
        type: string
        required: true
