version: 0.0.1
description: This module provides access to file storage.
objects:
  filesystemstorage.FileSystemSvc:
    type: service
    description: File system storage service
    request:
      params:        
        Data:
          type: files
        bucket:
          type: string
    configurations:
      filestoragedir:
        description: Directory to be used by the storage component
        type: string
      defaultbucket:
        description: Default Bucket to be used by the storage component
        type: string
params:
  filestoragedir: 
    type: string
    description: Directory to be used for storing files
  defaultbucket:
    description: Default Bucket to be used by the storage component
    type: string
