version: 0.0.1
description: Module provides entity displys
ui:
  skipUIModules: true
  externals:
    babel-runtime: babel-runtime
    babel-polyfill: babel-polyfill
    react: react
    prop-types: prop-types
  packages:
    react: "^16.1.0"
    prop-types: "^15.6.0"
