version: 0.0.1
description: Module provides entity displys
ui:
  js:
    skipUIModules: true
    externals:
      react: react
      prop-types: prop-types
    packages:
      react: "^16.1.0"
      prop-types: "^15.6.0"
