channels:
- name:  uiapp.app{{var "uiapplication" "."}}
  parent: root
  method: GET
  service: uiapp.files{{var "uiapplication" "."}}
  path: /modules{{var "uiapplication" "."}}.js
  skipauth: {{is "authenticateui" | not}}
  staticvalues:
    file: modules.js
- name: uiapp.services{{var "uiapplication" "."}}
  parent: root
  method: GET
  service:  uiapp.files{{var "uiapplication" "."}}
  path: /components{{var "uiapplication" "."}}.conf.js
  skipauth: {{is "authenticateui" | not}}
  staticvalues:
    file: components.conf.js
- name:  uiapp.boot{{var "uiapplication" "."}}
  parent: root
  method: GET
  service: uiapp.files{{var "uiapplication" "."}}
  path: /boot{{var "uiapplication" "."}}.js
  skipauth: {{is "authenticateui" | not}}
  staticvalues:
    file: boot.js
- name: uiapp.style{{var "uiapplication" "."}}
  parent: root
  method: GET
  service: uiapp.files{{var "uiapplication" "."}}
  path: /app{{var "uiapplication" "."}}.css
  skipauth: {{is "authenticateui" | not}}
  staticvalues:
    file: app.css
- name: uiapp.wasm{{var "uiapplication" "."}}
  parent: root
  method: GET
  service: uiapp.files{{var "uiapplication" "."}}
  path: /wasm{{var "uiapplication" "."}}.json
  skipauth: {{is "authenticateui" | not}}
  staticvalues:
    file: wasm.json
- name: uiapp.vendor{{var "uiapplication" "."}}
  parent: root
  method: GET
  service: uiapp.files{{var "uiapplication" "."}}
  path: /vendor{{var "uiapplication" "."}}.js
  skipauth: {{is "authenticateui" | not}}
  staticvalues:
    file: vendor.js
