channels:
- name:  uiapp.app{{var "application" "."}}
  parent: root
  method: GET
  service: uiapp.files{{var "application" "."}}
  path: /app{{var "application" "."}}.js
  staticvalues:
    file: app.js
- name: uiapp.services{{var "application" "."}}
  parent: root
  method: GET
  service:  uiapp.files{{var "application" "."}}
  path: /services{{var "application" "."}}.conf.js
  staticvalues:
    file: services.conf.js
- name: uiapp.style{{var "application" "."}}
  parent: root
  method: GET
  service: uiapp.files{{var "application" "."}}
  path: /app{{var "application" "."}}.css
  staticvalues:
    file: app.css
- name: uiapp.wasm{{var "application" "."}}
  parent: root
  method: GET
  service: uiapp.files{{var "application" "."}}
  path: /app{{var "application" "."}}.wasm
  staticvalues:
    file: app.wasm
- name: uiapp.vendor{{var "application" "."}}
  parent: root
  method: GET
  service: uiapp.files{{var "application" "."}}
  path: /vendor{{var "application" "."}}.js
  staticvalues:
    file: vendor.js
