version: 0.0.1
dependencies:
  reactwebcommon: ">=0.0.1"
  uicommon: ">=0.0.1"
  reactpages: ">=0.0.1"
description: Module provides entity list field for forms
ui:
  js:
    skipUIModules: true
    externals:
      babel-runtime: babel-runtime
      babel-polyfill: babel-polyfill
      redux: redux
      redux-form: redux-form
      reactpages: reactpages
      react: react
      react-redux: react-redux
      react-dom: react-dom
      redux-saga: redux-saga
      reactwebcommon: reactwebcommon
      uicommon: uicommon
    packages:
      react: "^16.1.0"
