version: 0.0.1
dependencies:
  staticfileserver: ">=0.0.1"
  filesystemstorage: ">=0.0.1"
  jsui: ">=0.0.1"
description: 'This module provides a simple web application shell with /index 
  routes using the files provided in the files directory of the module. '
ui:
  js:
    skipUIModules: true
modules:
  jsui:
    module: jsui
    settings:
      uiapplication: {{var "uiapplication"}}
params:
  uiapplication: 
    type: string
    description: Application to be started by the shell
  indexpath: 
    type: string
    description: Path to be used by the shell
    default: /index
  authenticateshell: 
    type: bool
    description: Authentication needed for shell 
    default: false
  authenticatescripts:
    type: bool
    description: Authentication needed for shell 
    default: false
