version: "0.0.1"
dependencies:
description: "Module provides ui module aggregation services. "
objects:
 ui:
  type: service
  description: "This service is a plugin for module manager and provides aggregation services"
  request:
    params:
        module:
            type: string
            required: true
            description: Module to be served for hot reload
  configurations:
   uifile:
    description: "Storage service from which files are to be served"
    type: string
    default: "index.js"
   application:
    description: "Name of the application being served"
    type: string
    default: app
   descriptor:
    description: "Operation to perform on a file"
    type: string
    default: "webdescriptor.js"
   properties_ext:
    description: "Extension to use on properties"
    type: string
    default: ".json"
   mergeduifile:
    description: "Name of the merged ui file to be created"
    type: string
    default: "app.js"
   mergedcssfile:
    description: "Name of the merged css file to be created"
    type: string
    default: "app.css"
   mergedwasmjson:
    description: "Name of the merged wasm json file to be created"
    type: string
    default: "wasm.json"
   mergedvendorfile:
    description: "Name of the merged vendor file to be created"
    type: string
    default: "vendor.js"
   mergeduidescriptor:
    description: "Name of the merged descriptor file to be created"
    type: string
    default: "services.conf.js"
   hotmodules: 
    type: stringmap
    description: Hot modules for development
params:
 application: 
    type: string
    description: "Name of the application being served by this instance"
 hotmodules: 
    type: stringmap
    description: Hot modules for development
