version: 0.0.1
dependencies:
  reactwebcommon: ">=0.0.1"
  entity: ">=0.0.1"
  uicommon: ">=0.0.1"
  reactpages: ">=0.0.1"
description: Module provides organization heirarchy
objects:   
modules:
  orgnode:
    module: entity
    settings:
      object: organization.OrgNode
      parent: root
      #instance: OrgNode
      dataservicefactory: mongodatabase
      create_dataservice: true
      create_dataadapterfactory: true
      create_getservice: true
      create_updateservice: true
      create_selectservice: true
      create_saveservice: true
      create_objectchannel: true
      list_page: true
      list_view: true
  job:
    module: entity
    settings:
      object: organization.Job
      parent: root
      #instance: Job
      dataservicefactory: mongodatabase
      create_dataservice: true
      create_dataadapterfactory: true
      create_getservice: true
      create_updateservice: true
      create_selectservice: true
      create_saveservice: true
      create_objectchannel: true
      list_page: true
      list_view: true
  employee:
    module: entity
    settings:
      object: organization.Employee
      parent: root
      #instance: Employee
      dataservicefactory: mongodatabase
      create_dataservice: true
      create_dataadapterfactory: true
      create_getservice: true
      create_updateservice: true
      create_selectservice: true
      create_saveservice: true
      create_objectchannel: true
      list_page: true
      list_view: true
ui:
  js:
    externals:
      react: react
      uicommon: uicommon
      redux-saga: redux-saga
      redux: redux
      react-redux: react-redux
      reactpages: reactpages
      reactwebcommon: reactwebcommon
      sanitize-html: sanitize-html
      prop-types: prop-types
    packages:
      react: "^16.8.0"
      redux-saga: "^1.1.1"
