version: 0.0.1
dependencies:
  entity: ">=0.0.1"
description: Module provides solution entity
modules:
  default:
    module: entity
    settings:
      object: Solution
      parent: root
      instance: Solution
      dataservicefactory: mongodatabase
ui:
  skipUIModules: true
