version: 0.0.1
dependencies:
  reactwebcommon: ">=0.0.1"
  entity: ">=0.0.1"
  uicommon: ">=0.0.1"
description: Module provides designer ui components
objects:
  objectsresolver:
    type: service
    description: Service for resolving module objects factories and dependencies
    configurations:
      objecttype:
        type: string
        required: true
        description: Type of the object being resolved
modules:
  environment:
    module: entity
    settings:
      object: Environment
      parent: root
      instance: Environment
      dataservicefactory: mongodatabase
  application:
    module: entity
    settings:
      object: Application
      parent: root
      instance: Application
      dataservicefactory: mongodatabase
  module:
    module: entity
    settings:
      object: Module
      parent: root
      instance: Module
      dataservicefactory: mongodatabase
  moduleinstance:
    module: entity
    settings:
      object: ModuleInstance
      parent: root
      instance: ModuleInstance
      dataservicefactory: mongodatabase
  factory:
    module: entity
    settings:
      object: Factory
      parent: root
      instance: Factory
      dataservicefactory: mongodatabase
  service:
    module: entity
    settings:
      object: Service
      parent: root
      instance: Service
      dataservicefactory: mongodatabase
  param:
    module: entity
    settings:
      object: Param
      parent: root
      instance: Param
      dataservicefactory: mongodatabase
  channel:
    module: entity
    settings:
      object: Channel
      parent: root
      instance: Channel
      dataservicefactory: mongodatabase
  rule:
    module: entity
    settings:
      object: Rule
      parent: root
      instance: Rule
      dataservicefactory: mongodatabase
  task:
    module: entity
    settings:
      object: Task
      parent: root
      instance: Task
      dataservicefactory: mongodatabase
  entity:
    module: entity
    settings:
      object: Entity
      parent: root
      instance: Entity
      dataservicefactory: mongodatabase
  field:
    module: entity
    settings:
      object: Field
      parent: root
      instance: Field
      dataservicefactory: mongodatabase
  engine:
    module: entity
    settings:
      object: Engine
      parent: root
      instance: Engine
      dataservicefactory: mongodatabase
  solution:
    module: entity
    settings:
      object: Solution
      parent: root
      instance: Solution
      dataservicefactory: mongodatabase
  security:
    module: entity
    settings:
      object: Security
      parent: root
      instance: Security
      dataservicefactory: mongodatabase
  server:
    module: entity
    settings:
      object: Server
      parent: root
      instance: Server
      dataservicefactory: mongodatabase
ui:
  externals:
    react: react
    uicommon: uicommon
    redux-saga: redux-saga
  packages:
    react: "^16.3.0"
    redux-saga: "^0.16.0"
