version: 0.0.1
dependencies:
  reactwebcommon: ">=0.0.1"
  entity: ">=0.0.1"
  uicommon: ">=0.0.1"
  modulesbase: ">=0.0.1"
  reactpages: ">=0.0.1"
description: Module provides designer ui components
objects:
  objectsresolver:
    type: service
    description: Service for resolving module objects factories and dependencies
    configurations:
      objecttype:
        type: string
        required: true
        description: Type of the object being resolved
modules:
  environment:
    module: entity
    settings:
      object: Environment
      parent: root
      instance: Environment
      dataservicefactory: mongodatabase
      create_dataservice: true
      create_dataadapterfactory: true
      create_getservice: true
      create_updateservice: true
      create_selectservice: true
      create_saveservice: true
      create_objectchannel: true
      list_page: true
      new_form: true
      new_form_page: true
      update_form: true
      update_form_page: true
      list_view: true
      embedded_doc_search: true
      list_view_args: 
        Solution: 
          Id: {{jsreplace "Application.Route.Params.solutionId"}}
      form_new_args:
        Solution: 
          Id: {{jsreplace "Application.Route.Params.solutionId"}}
          Type: Solution
  application:
    module: entity
    settings:
      object: Application
      parent: root
      instance: Application
      dataservicefactory: mongodatabase
      embedded_doc_search: true
      create_dataservice: true
      create_dataadapterfactory: true
      create_getservice: true
      create_updateservice: true
      create_selectservice: true
      create_saveservice: true
      create_objectchannel: true
      list_page: true
      new_form: true
      new_form_page: true
      update_form: true
      update_form_page: true
      list_view: true
      list_view_args: 
        Solution: 
          Id: {{jsreplace "Application.Route.Params.solutionId"}}
      form_new_args:
        Solution: 
          Id: {{jsreplace "Application.Route.Params.solutionId"}}
          Type: Solution
  server:
    module: entity
    settings:
      object: Server
      parent: root
      instance: Server
      dataservicefactory: mongodatabase
      create_dataservice: true
      create_dataadapterfactory: true
      create_getservice: true
      create_updateservice: true
      create_selectservice: true
      create_saveservice: true
      create_objectchannel: true
      list_page: true
      new_form: true
      new_form_page: true
      update_form: true
      update_form_page: true
      list_view: true
      embedded_doc_search: true
      list_view_args: 
        Solution: 
          Id: {{jsreplace "Application.Route.Params.solutionId"}}
      form_new_args:
        Solution: 
          Id: {{jsreplace "Application.Route.Params.solutionId"}}
          Type: Solution
  moduleinstance: 
    module: entity
    settings:
      object: ModuleInstance
      parent: root
      instance: ModuleInstance
      skipData: true
      new_form: true
      new_form_page: true
  factory:
    module: entity
    settings:
      object: Factory
      parent: root
      instance: Factory
      skipData: true
      new_form: true
      new_form_page: true
  service:
    module: entity
    settings:
      object: Service
      parent: root
      instance: Service
      skipData: true
      new_form: true
      new_form_page: true
  channel:
    module: entity
    settings:
      object: Channel
      parent: root
      instance: Channel
      skipData: true
      new_form: true
      new_form_page: true
  rule:
    module: entity
    settings:
      object: Rule
      parent: root
      instance: Rule
      skipData: true
      new_form: true
      new_form_page: true
  task:
    module: entity
    settings:
      object: Task
      parent: root
      instance: Task
      skipData: true
      new_form: true
      new_form_page: true
  entity:
    module: entity
    settings:
      object: Entity
      parent: root
      instance: Entity
      skipData: true
      new_form: true
      new_form_page: true
  engine:
    module: entity
    settings:
      object: Engine
      parent: root
      instance: Engine
      skipData: true
      new_form: true
      new_form_page: true
  field:
    module: entity
    settings:
      object: Field
      parent: root
      instance: Field
      skipData: true
      new_form: true
      new_form_page: true
  security:
    module: entity
    settings:
      object: Security
      parent: root
      instance: Security
      skipData: true
      new_form: true
      new_form_page: true
  configform: 
    module: entity
    settings:
      object: ConfigForm
      parent: root
      instance: ConfigForm
      dataservicefactory: mongodatabase
      create_dataservice: true
      create_dataadapterfactory: true
      create_objectchannel: true
      create_getservice: true
  entitlements:
    module: entity
    settings:
      object: Entitlement
      parent: root
      instance: Entitlement
      skipData: true
      list_view: true
      list_view_mode: edit_module
      list_view_args: 
        Solution: 
          Id: {{jsreplace "Application.Route.Params.solutionId"}}
      new_form: true
      new_form_page: true
      form_new_args:
        Local: true
        Solution: 
          Id: {{jsreplace "Application.Route.Params.solutionId"}}
          Type: Solution
ui:
  js:
    externals:
      react: react
      uicommon: uicommon
      redux-saga: redux-saga
      redux: redux
      react-redux: react-redux
      reactpages: reactpages
      reactwebcommon: reactwebcommon
      sanitize-html: sanitize-html
      prop-types: prop-types
    packages:
      react: "^16.8.0"
      redux-saga: "^1.1.1"
