version: 0.0.1
dependencies:
  reactwebcommon: ">=0.0.1"
  laatoositetheme: ">=0.0.1"
description: Module provides module designer theme
extends: laatoositetheme
settings:
  infoBlock: signin
  showMenu: true
  menu:
  - homepage:
    title: Account
    page: account
  - Solutions:
    title: Solutions
    page: list_solution
  - AllModules:
    title: AllModules
    page: modulesrepo
ui:
  js:
    skipUIModules: true
    externals:
      reactwebcommon: reactwebcommon
      laatoositetheme: laatoositetheme
