version: 0.0.1
dependencies:
  reactwebcommon: ">=0.0.1"
  laatoositetheme: ">=0.0.1"
description: Module provides laatoo theme
extends: laatoositetheme
settings:
  infoBlock: designerlink
ui:
  js:
    skipUIModules: true
    externals:
      reactwebcommon: reactwebcommon
      laatoositetheme: laatoositetheme
