version: 0.0.1
dependencies:
  reactwebcommon: ">=0.0.1"
description: Module provides laatoo theme
modules:
  def:
    module: laatoositetheme
    settings:
      headertitle: Laatoo
      className: laatoodashboard
      vertical: true
ui:
  js:
    skipUIModules: true
