version: 0.0.1
dependencies:
  reactwebcommon: ">=0.0.1"
description: Module provides laatoo theme
modules:
  def:
    module: laatoositetheme
    settings:
      className: laatoodashboard
      infoBlock: InfoBlock
      showMenu: true
ui:
  js:
    skipUIModules: true
