version: 0.0.1
object: EntityModule
dependencies:
  dataadapter: ">=0.0.1"
  uicommon: ">=0.0.1"
  reactwebcommon: ">=0.0.1"
description: This module provides an entity object services, channels, forms, views
  etc
ui:
  js:
    externals:
      dataadapter: dataadapter
      uicommon: uicommon
      reactwebcommon: reactwebcommon
      react: react
      prop-types: prop-types
      core-js: core-js
    packages:
      react: "^16.8.0"
      prop-types: "^15.6.0"
      core-js: "^3.1.0"
objects:
  EntityModule:
    type: module
    configurations:
      object:
        type: string
        description: Object for which services are being created
        required: true
      new_form: 
        type: bool
        description: True if new entity form needs to be created by entity module
      update_form: 
        type: bool
        description: True if new update form needs to be created by entity module
      new_form_page: 
        type: bool
        description: True if new entity page needs to be created by entity module
      update_form_page: 
        type: bool
        description: True if update entity page needs to be created by entity module
      update_success_route:
        type: string
        description: Route for update success
      instance:
        type: string
        description: Discriminator to distinguish multiple services created by multiple
          instances of the module
modules:
  data:
    module: dataadapter
    skip: {{var "skipData"}}
    settings:
      object: {{var "object"}}
      parent: {{var "parent"}}
      instance: {{var "instance"}}
      dataservicefactory: {{var "dataservicefactory"}}
      embedded_doc_search: {{var "embedded_doc_search"}}
      create_dataservice: {{var "create_dataservice"}}
      create_getservice: {{var "create_getservice"}}
      create_saveservice: {{var "create_saveservice"}}
      create_updateservice: {{var "create_updateservice"}}
      create_selectservice: {{var "create_selectservice"}}
      create_dataadapterfactory: {{var "create_dataadapterfactory"}}
      create_objectchannel: {{var "create_objectchannel"}}
params:
  object: 
    type: string
    description: Name of entity user object
  parent: 
    type: string
    description: Parent channel to be used for entity APIs
  instance: 
    type: string
    description: Name of the instance (e.g. myuser instead of user ) to be used for the
      object. Defaults to object name
  dataservicefactory: 
    type: string
    description: Data service factory to be used for entity storing
  list_page_route: 
    type: string
    description: Route for the list page on spa ui. Default route /list_instance
  new_form_route: 
    type: string
    description: Route for the new entity page on application ui. Default route /new_form_instance
  update_form_route: 
    type: string
    description: Route for the update entity page on application ui. Default route /update_form_instance/:entityId
  view_page_route: 
    type: string
    description: Route for the view page route on application ui. Default route /instance/:entityId
  list_view_args: 
    type: stringmap
    description: Filter args for list view
  embedded_doc_search: 
    type: bool
    description: Allow embedded document search in list screen
  form_new_args: 
    type: stringmap
    description: State params for new form
  list_page: 
    type: bool
    description: True if list page needs to be created by entity module
  new_form: 
    type: bool
    description: True if new entity form needs to be created by entity module
  new_form_page: 
    type: bool
    description: True if new entity page needs to be created by entity module
  update_form: 
    type: bool
    description: True if update form needs to be created by entity module
  update_form_page: 
    type: bool
    description: True if update form page needs to be created by entity module
  update_success_route: 
    type: string
    description: Route to go to after success of update form. Goes to list page by default
  view_page: 
    type: bool
    description: True if entity view page needs to be created by entity module
  list_view: 
    type: bool
    description: True if list view needs to be created by entity module
  skipData:
    type: bool
    description: Skip data adapter services for entity
  list_actionbar:
    type: string
    description: Action bar on list page of entity.
  list_view_mode:
    type: string
    description: List view mode 
  create_dataservice:
    type: bool
    description: Data service for object
  create_getservice:
    type: bool
    description: Get data service
  create_saveservice:
    type: bool
    description: Save data service
  create_updateservice:
    type: bool
    description: Update data service
  create_selectservice:
    type: bool
    description: Select data service
  create_dataadapterfactory:
    type: bool
    description: Create data adapter factory
  create_objectchannel:
    type: bool
    description: Create object primary channel
