version: 0.0.1
object: EntityModule
dependencies:
  dataadapter: ">=0.0.1"
  uicommon: ">=0.0.1"
  reactwebcommon: ">=0.0.1"
description: This module provides an entity object services, channels, forms, views
  etc
ui:
  skipUIModules: true
  externals:
    dataadapter: dataadapter
    uicommon: uicommon
    reactwebcommon: reactwebcommon
    babel-runtime: babel-runtime
    babel-polyfill: babel-polyfill
    react: react
    prop-types: prop-types
  packages:
    react: "^16.1.0"
    prop-types: "^15.6.0"
objects:
  EntityModule:
    type: module
    configurations:
      object:
        type: string
        description: Object for which services are being created
        required: true
      instance:
        type: string
        description: Discriminator to distinguish multiple services created by multiple
          instances of the module
modules:
  data:
    module: dataadapter
    settings:
      object: {{var "object"}}
      parent: {{var "parent"}}
      instance: {{var "instance"}}
      dataservicefactory: {{var "dataservicefactory"}}
params:
  object: 
    type: string
    description: Name of entity user object
  parent: 
    type: string
    description: Parent channel to be used for entity APIs
  instance: 
    type: string
    description: Name of the instance (e.g. myuser instead of user ) to be used for the
      object. Defaults to object name
  dataservicefactory: 
    type: string
    description: Data service factory to be used for entity storing
  list_page_route: 
    type: string
    description: Route for the list page on spa ui. Default route /list_instance
  new_form_route: 
    type: string
    description: Route for the new entity page on application ui. Default route /new_form_instance
  update_form_route: 
    type: string
    description: Route for the update entity page on application ui. Default route /update_form_instance/:entityId
  view_page_route: 
    type: string
    description: Route for the view page route on application ui. Default route /instance/:entityId
  list_view_args: 
    type: string
    description: Filter args for list view
  skipItems: 
    type: string
    description: Items to be skipped for an entity. list_page, new_form, update_form, view_page, list_view
