version: 0.0.1
dependencies:
  entity: ">=0.0.1"
description: Module provides server entity
modules:
  default:
    module: entity
    settings:
      object: Server
      parent: root
      instance: Server
      dataservicefactory: mongodatabase
ui:
  skipUIModules: true
