name: shell.index{{var "module" "."}}
servicemethod: named_files_service
files:
  index.html:
    cache: 'true'
    path: index{{var "module" "."}}.html
    replacements:
      - search: <<routeinfo>>
        method: routeinfo
storage: shell.filesstorage