version: 0.0.1
dependencies:
  uicommon: ">=0.0.1"
  reactpages: ">=0.0.1"
description: Module provides base for react based applications of laatoo.
ui:
  skipUIModules: true
  externals:
    babel-runtime: babel-runtime
    babel-polyfill: babel-polyfill
    react: react
    react-redux: react-redux
    reactpages: reactpages
    uicommon: uicommon
    redux: redux
    redux-saga: redux-saga
    prop-types: prop-types
  packages:
    react: "^15.6.1"
    react-redux: "^5.0.6"
    redux: "^3.7.2"
    redux-saga: "^0.15.6"
    prop-types: "^15.5.10"
params:
  uikit: Uikit to be used by laatoo react application
  theme: Theme to be used by laatoo react application
  router: Router to be used by laatoo react application
