version: 0.0.1
description: This module provides access to google storage service. By default a service
  server.googlestorage is created.
objects:
  googlestorage.GoogleStorageSvc:
    type: service
    description: Google storage service
    request:
      params:        
        Data:
          type: files
        bucket:
          type: string
    configurations:
      googlestoragebucket:
        description: Bucket to be used by the storage component
        type: string
        required: true
params:
  googlestoragebucket: 
    type: string
    description: Bucket to be used by google storage service
