version: 0.0.1
description: Module provides director router kit for laatoo react applications
ui:
  skipUIModules: true
  externals:
    react: react
    director: director
    redux-director: redux-director
  packages:
    react: "^15.6.1"
    director: "^1.2.8"
    redux-director: "^0.2.5"
