route: "/budgets/configuration"
authenticate: true
component:
  type: layout
  layout: 2col
  leftcol:
    type: menu
    id: budgets
    vertical: true
  rightcol: 
    type: block
    id: configurebudget