version: 0.0.1
description: 'Module provides web common components. '
ui:
  skipUIModules: true
  externals:
    react: react
    sanitize-html: sanitize-html
  packages:
    react: "^15.6.1"
    sanitize-html: "^1.14.1"
