servicemethod: cadence_simpleworkflow
skip: {{if exists "emailverification"}} {{var "emailverification" | not}} {{else}} true {{end}}
workflowname: laatoo.signup
workflow:
  - laatoo.signup.email
  - laatoo.signup.verify
  - laatoo.signup.approve
