servicemethod: SignupEmailTask
SiteName: {{var "sitename"}}
SiteLink: {{var "sitelink"}}/verifyemail
MailBody: {{if exists "mailbody"}} {{var "mailbody"}} {{else}} '<html><body>Hi <<.Name>><br/><p> This is a verification email from <<.SiteName>>. Please click on this link to verify your email Id <a href="<<.SiteLink>>/<<.Token>>" style="color: green;">Click here</a></p></body></html>' {{end}}
Key: {{var "key"}}
