servicemethod: signup.RegistrationService
#skip: {{if exists "signup_support"}} {{var "signup_support" | not}} {{else}} true {{end}}
#dataobject: stringmap
user_data_svc: dataadapter.dataservice.User
def_role: {{var "defaultrole"}}
emailverification: {{if exists "emailverification"}} {{var "emailverification"}} {{else}} false {{end}}
emailqueue: laatoo.signup.email
emailworkflowsupport: {{if exists "emailworkflowsupport"}} {{var "emailworkflowsupport"}} {{else}} false {{end}}
emailverificationworkflow: {{if exists "emailverificationworkflow"}} {{var "emailverificationworkflow"}} {{else}} laatoo.signup {{end}}
workflowinitiator: {{if exists "workflowinitiator"}} {{var "workflowinitiator"}} {{else}} laatoo.workflowinitiator {{end}}