version: '3'
services:
  designer:
    build:
      context: .
      dockerfile: Dockerfile.designertest
    volumes:
    - /home/mandeep/goprogs/src/laatoo/designer/dist/config/designer:/config/environments/designer
    - /home/mandeep/goprogs/src/laatoo/dist/bin:/bin
    - /home/mandeep/goprogs/src/laatoo/designer/dist/appfiles:/bin/appfiles
    - /home/mandeep/goprogs/src/laatoo/designer/dist/publicdir:/bin/publicdir
    - /home/mandeep/goprogs/src/laatoo/designer/modules:/modules
    - /home/mandeep/goprogs/src/laatoo/designer/modulesrepo:/modulesrepo
    - /home/mandeep/goprogs/src/laatoo:/devmodulesrepo
    ports:
     - "6060:6060"
    depends_on:
    - mongo
    environment:
     - LAATOO_mongoconnectionstring=mongo
  mongo:
    image: mongo
    ports:
     - "27017:27017"
    volumes:
    - /backups/punjabimehfilmongo:/data/db
volumes:
  logvolume01: {}
